export const MAIL_RETENTION_HOURS = 1;
export const MAIL_RETENTION_MS = MAIL_RETENTION_HOURS * 60 * 60 * 1000;

export const SESSION_RETENTION_HOURS = 24;
export const SESSION_RETENTION_MS =
	SESSION_RETENTION_HOURS * 60 * 60 * 1000;
